"""edit table

Revision ID: 57c8ef64fc02
Revises: 27a31c0ad9d7
Create Date: 2024-12-07 20:17:00.187398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c8ef64fc02'
down_revision: Union[str, None] = '27a31c0ad9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###
